### ISSUE TITLE
Missing h5pyd package requirement

### ISSUE THREAD

**Issue by brynpickering** [NREL/OpenOA#116]
The required dependency `h5pyd` is missing following a fresh install of OpenOA. 

This causes an error in the file `operational_analysis/methods/quality_check_automation.py`. This error is not caught by tests since the file coverage is 0%. It may be a good idea to just have a test to try importing every function in the package, to avoid this issue in future.

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2171)

**Comment by jordanperr** [comment]
Good catch. And no, we do not have any test coverage for this file, which is the root of the problem. We have had some internal discussions over whether or not to require h5pyd in the general requirements, since many users may not use the quality_check_automation.py module. However, I agree that h5pyd should be added to the new example requirements, since it is required to run the example notebooks.

**Comment by brynpickering** [comment]
Hmm, since this is a requirement of the package (i.e. it is explicitly imported in one of the package modules, even if that module is likely to be seldom used), it should probably be an installation requirement.

**Comment by jordanperr** [comment]
This was fixed in #117
