### ISSUE TITLE
Binder fails to setup environment

### ISSUE THREAD

**Issue by ghylander** [NREL/OpenOA#144]
I wanted to try the repo to check OpenOA's capabilities and relevance tothe work i'm developing, but the binder environment fails to build

![image](https://user-images.githubusercontent.com/74593034/116518471-8f8d5400-a8d0-11eb-9e7c-5faa658369e3.png)

**Comment by charlie9578** [comment]
Hi Gustavo, 

There's a patch for this waiting to be pushed to main. For now you can use the develop branch as a workaround: https://mybinder.org/v2/gh/NREL/OpenOA/develop?filepath=examples. 

For me there's also an issue with the "Launch Binder" link in GitHub, in that it refers to "master" instead of "main," so I think the url will also need updating once the patch is pushed to main to make things work first time.

Cheers,
Charlie

**Comment by jordanperr** [comment]
Thanks! I have updated the Binder link in the develop branch. As @charlie9578 said, the version specifier bug has been fixed in the develop branch. I'll close this issue once we make the next release.

**Comment by jordanperr** [comment]
V2.2 has been merged into master and I've confirmed the Binder button is working again. Thank you for reporting this!
