### ISSUE TITLE
Better contributor recognition

### ISSUE THREAD

**Issue by Dynorat** [NREL/OpenOA#166]
HI All,
I stumbled across this project and thought it might be an interesting addition to OpenOA as we look to scale with more contributors.   

https://github.com/all-contributors/all-contributors

**Comment by Dynorat** [comment]
developer group decided this would be good to execute.  Will work on implementing this: https://allcontributors.org/docs/en/bot/installation

**Comment by jordanperr** [comment]
I think something like this would be great. We currently just have an alphabetical list of contributors in the readme, which is not very helpful in determining who the top contributors are. Instead of using a 3rd party application, could we simply link to this page?: https://github.com/NREL/OpenOA/graphs/contributors

**Comment by RHammond2** [comment]
Using the contributors graph is definitely an easy add-on, but I think the advantage or the All Contributors bot is that it allows for non-code contribution recognition, as opposed to using a basis of the number of lines of code contributed. @Dynorat, is that a good assessment of the benefit-add of a third-party linkage? And is help still wanted?

**Comment by Dynorat** [comment]
I suggest we implement this as part of the V3 release.  I can update the milestone.  @RHammond2 you want to implement this or shall I?

**Comment by RHammond2** [comment]
Implemented in the v3.1 release.
