### ISSUE TITLE
Hard-coded re-analysis end date

### ISSUE THREAD

**Issue by victor-e-castaneda** [NREL/OpenOA#170]
There is a hard-coded date for the reanalysis aggregation which limits the analysis of recently built wind farms. 

https://github.com/NREL/OpenOA/blob/b802df67a72059b40bb8bf21fc87c5dfdc52889d/operational_analysis/methods/plant_analysis.py#L509

The end date then truncates the data frame in this line

https://github.com/NREL/OpenOA/blob/b802df67a72059b40bb8bf21fc87c5dfdc52889d/operational_analysis/methods/plant_analysis.py#L398-L400

Should this end date range be increased? Or at the very least passed as a variable?

**Comment by ejsimley** [comment]
Thanks for pointing out this issue @victor-e-castaneda. I agree these dates should not be hard-coded in. That's a good idea to include the option to define the date range as an argument and it makes sense to determine default dates based on the period of record of the operational data for the plant. We'll work on a solution to this for the V2.3 release!

**Comment by ejsimley** [comment]
@victor-e-castaneda I wanted to let you now that we just merged in PR #180 which fixes this issue. The end date for the reanalysis data is now automatically determined as the last full month when all reanalysis products contain data. There is also an optional argument to the `MonteCarloAEP` class to specify a particular end date if desired. Note that the start date is also automatically determined as the latest start date of all the reanalysis products. There's no option to specify a particular start date, though, because the long-term correction always uses X number of years backwards in time from the end date.

We'll merge this code from develop to the main branch in a few days for the version 2.3 release. 

Thanks again for bringing this to our attention!
