### ISSUE TITLE
Validation of reanalysis data is too limiting

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#216]
Hi, 

I think the validator for the reanalysis datasets limits them specifically to those called "merra2", "ncep2", "erai" and "era5." I propose removing this requirement, as I wanted to add "era5_monthly" as a dataset, and I'm sure other people will have other datasets too, which might not have these names. In the end I used "erai" to avoid touching the aep.py file!

Thanks,
Charlie

**Comment by RHammond2** [comment]
Hi @charlie9578,

Thanks for the feedback, we noticed that this might not be the best way forward when working on the v3rc1 release, though we didn't change the current functionality in that release. Our initial thinking is to remove any hard limitations on what the naming convention is, and allow free-form input. Is this the type of solution you were thinking, or did you have something else in mind?

Best,
Rob

**Comment by charlie9578** [comment]
Hi Rob, yes, that's all I was thinking. Thanks, Charlie

**Comment by charlie9578** [comment]
Hi,

For running "project_Cubico" I just made the following update to the reanalysis validator:

`member_validator=attrs.validators.instance_of(str)`

which means any name can then be used for the reanalysis data sets.

Thanks,
Charlie

**Comment by RHammond2** [comment]
Thanks, @charlie9578! While I think the approach in theory is nice, in practical terms it will fail when no reanalysis data is passed in because there isn't a conditional evaluation of attrs validators (something I've desired many times now). Currently I have just removed the validation stage of the dictionary keys, but am in search of something a bit more automated and elegant like your proposal above.
