### ISSUE TITLE
Testing not being performed with new pull requests

### ISSUE THREAD

**Issue by moptis** [NREL/OpenOA#27]
@jordanperr 

I don't think Travis CI is running tests with each new pull request. Can you address this?

**Comment by jordanperr** [comment]
This seems to be caused by an API change between Github and Travis-ci. They're switching to a new integration called "Github Apps" instead of using Webhooks. The pull requests were building, but the "github check" on the pull request was not being activated. Therefore you couldn't see the result of the build inside Github. I installed the travis-ci "Github App" - and it looks like PRs checks are working again.

If the check doesn't work in the future, please navigate to: https://travis-ci.org/NREL/OpenOA/pull_requests
where you can see all the pull requests built by Travis-ci.
