### ISSUE TITLE
Problem with spline curve fitting

### ISSUE THREAD

**Issue by pooranasaviour** [NREL/OpenOA#53]
Hallo, I have a small issue when plotting the power curve using the toolkit below. How to get rid of this issue? Any suggestions? P.S. I have no issues when I plot the iec curve. The problem occurs only in the spline_curve plot. 
Code: spline_curve = power_curve.gam(windspeed_romo, power_kw_romo, n_splines=20)
Error: y data must not contain Inf nor NaN

Thank you.

**Comment by jordanperr** [comment]
Hi @pooranasaviour, thanks for reporting this to the issue tracker! Judging by the error message it appears that power_kw_romo may contains unacceptable (out of range) values. Could you please verify the following statement returns True?

numpy.isfinite(power_kw_romo).all()

If it returns false, this means there is some bad value in the power_kw_romo array. Please remove the bad value and try fitting the curve again.

If it returns true, then could you please provide me with the values of windspeed_romo and power_kw_romo so that I can try and reproduce the error.

**Comment by pooranasaviour** [comment]
Hi @Jordanperr, I checked, made some corrections and filtering in the dataframe and then it worked. Thank you so much.
